name: diploma-generator
description: Spring Boot Diploma Generator

services:
  - name: web
    type: web
    build:
      type: dockerfile
      dockerfile: Dockerfile
    ports:
      - port: 8080
        protocol: http
    resources:
      cpu: 100
      memory: 512
      storage: 1
    scaling:
      min: 1
      max: 1
    healthCheck:
      path: /
      port: 8080
      initialDelay: 30
